# Generated by Django 6.0 on 2025-12-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_certificate_id_alter_checkin_id_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='school_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='semester',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
