# Generated by Django 6.0 on 2025-12-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_school_year_event_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_font_styles',
            field=models.JSONField(blank=True, default=dict, help_text='Stores font sizes and colors for certificate text fields'),
        ),
    ]
