# Generated by Django 6.0 on 2025-12-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
